name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21' # or whichever version you need

    - name: Install dependencies
      run: npm install # or yarn install, depending on your project setup

    - name: Build project
      run: npm run build # or whatever command you use to build your project
      
    - name: Copy build folder to gh-pages branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r build .
        git add .
        git commit -m "Deployed from main branch"
        git push origin gh-pages --force
